# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = "$directory$python$line_break$character"
right_format = "${custom.jj}"

[character]
success_symbol = '[>>>](bold yellow)'
error_symbol = "[>>>](bold red)"

[python]
format = '[py:$virtualenv-$version]($style)'

[cmd_duration]
disabled = true

[package]
disabled = true

[directory]
truncation_length = 0
style = 'fg:red'
truncate_to_repo = false

[custom.jj]
command = ''' jj log --no-graph -r @ -T 'if(self.empty(), "@", "@*") ++ ": " ++ self.parents().map(|p| if(p.bookmarks().len() > 0, p.bookmarks(), p.change_id().shortest()))' '''
when = 'jj root'
