alias ls='ls --color=auto '
alias ll='eza -la '
alias chmox='chmod +x '
alias pac='sudo pacman -S '
alias req='uv sync'
alias start='ssh-agent sway'
alias req='uv sync --all-groups'
alias ac='source .venv/bin/activate'
alias rmvenv='rm -r .venv/bin/activate'
alias mkvenv='uv venv -p 3.9'
alias chmox='chmod +x'
alias tmpdir='cd $(mktemp -d)'
