# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd extendedglob notify
unsetopt beep
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '~/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
bindkey '^P' history-beginning-search-backward
bindkey '^N' history-beginning-search-forward

# homebrew
if command -v /opt/homebrew/bin/brew > /dev/null 2>&1; then
  eval $(/opt/homebrew/bin/brew shellenv)
fi

# atuin
eval "$(atuin init zsh)"
