[user]
name = "Alec Snyder"
email = "linuxbash8@gmail.com"

[ui]
default-command = ["status"]
editor = "vim"
conflict-marker-style = "git"

[aliases]
bk = ["bookmark"]
push = ["git", "push"]
pull = ["git", "fetch"]
fork = ["new", "--after", "trunk()", "--before", "@", "--no-edit"]
clean = ["new", "all:bookmarks() & mine()"]
ll = ["log", "-r", "(trunk()..mine()):: | trunk()"]
la = ["log", "-r", "::"]

[git]
push-new-bookmarks = true
auto-local-bookmark = true

[merge-tools.pycharm]
program = "pycharm"
merge-args = ["merge", "$left", "$right", "$base", "$output"]
edit-args = ["diff", "$left", "$right"]

[revsets]
log = "trunk()..@ | trunk()"

[templates]
git_push_bookmark = '"alec/" ++ change_id.short()'
